package com.openlattice.chronicle.timeusediary

/**
 * @author alfoncenzioka &lt;alfonce@openlattice.com&gt;
 */
public class TimeUseDiarySummarizedDataVariables private constructor() {
    public companion object {
        public const val PRIMARY_BATHROOM_DURATION: String = "primary_bathroom_mins"
        public const val ADULT_MEDIA_BLOCKS: String =  "adultMedia_blocks"
        public const val SLEEP_ARRANGEMENT: String = "sleepArrangement"
        public const val BG_AUDIO_NIGHT: String = "bgAudioNight"
        public const val PRIMARY_CHILDCARE_BLOCKS: String = "primary_childcare_blocks"
        public const val PRIMARY_MEDIA_DURATION: String = "primary_media_mins"
        public const val DAY_TIME_END: String = "dayEndTime"
        public const val PRIMARY_MEDIA_CO_VIEWERS_BLOCKS: String = "primary_media_coviewers_blocks"
        public const val BD_MEDIA_DAY_BLOCKS: String = "bgMediaDay_blocks"
        public const val PRIMARY_CHILDCARE_DURATION: String = "primary_childcare_mins"
        public const val PRIMARY_PLAY_INSIDE_DURATION: String = "primary_play_inside_mins"
        public const val ADULT_MEDIA_DURATION: String = "adultMedia_mins"
        public const val DAY_OF_WEEK: String = "dayOfWeek"
        public const val TYPICAL_SLEEP_PATTERN: String = "typicalSleepPattern"
        public const val WAKE_UP_COUNT: String = "wakeUpCount"
        public const val BG_MEDIA_DAY_DURATION: String = "bgMediaDay_mins"
        public const val SCREEN_ONE_HOUR_FROM_SLEEPING_BLOCKS: String =  "screen_1hfromsleeping_blocks"
        public const val TYPICAL_DAY: String = "typicalDay"
        public const val SECONDARY_BOOK_TITLE: String = "secondaryBookTitle"
        public const val SCREEN_DURATION_PLAYING_PROPORTION: String = "screen_during_Playing_proportion"
        public const val PRIMARY_EATING_DURATION: String = "primary_eating_mins"
        public const val BG_TV_DAY_DURATION: String = "bgTvDay_mins"
        public const val PRIMARY_READING_DURATION: String = "primary_reading_mins"
        public const val PRIMARY_PLAY_INSIDE_BLOCKS: String =  "primary_play_inside_blocks"
        public const val TODAY_WAKE_UP_TIME: String = "todayWakeUpTime"
        public const val PRIMARY_OTHER_AT_HOME_BLOCKS: String = "primary_other_at_home_blocks"
        public const val PRIMARY_MEDIA_BLOCKS: String = "primary_media_blocks"
        public const val PRIMARY_BATHROOM_BLOCKS: String =  "primary_bathroom_blocks"
        public const val SCREEN_DURING_SLEEPING_DURATION: String = "screen_during_sleeping_proportion"
        public const val PRIMARY_OTHER_AT_HOME_DURATION: String = "primary_other_at_home_mins"
        public const val PRIMARY_MEDIA_NAME: String = "primaryMediaName"
        public const val BG_TV_DAY_BLOCKS: String =  "bgTvDay_blocks"
        public const val PRIMARY_MEDIA_CO_VIEWERS_DURATION: String =  "primary_media_coviewers_mins"
        public const val PRIMARY_MEDIA_PLAY_OUTSIDE_DURATION: String = "primary_play_outside_mins"
        public const val DAY_START_TIME: String =  "dayStartTime"
        public const val SCREEN_DURING_EATING_PROPORTION: String =  "screen_during_Eating_proportion"
        public const val BG_AUDIO_DAY_DURATION: String =  "bgAudioDay_mins"
        public const val NON_TYPICAL_DAY_REASON: String =  "nonTypicalDayReason"
        public const val PRIMARY_PLAY_OUTSIDE_BLOCKS: String = "primary_play_outside_blocks"
        public const val BG_TV_NIGHT: String =  "bgTvNight"
        public const val PRIMARY_READING_BLOCKS: String = "primary_reading_blocks"
        public const val BG_AUDIO_DAY_BLOCKS: String =  "bgAudioDay_blocks"
        public const val PRIMARY_EATING_BLOCKS: String =  "primary_eating_blocks"
        public const val PRIMARY_BOOK_TITLE: String =  "primaryBookTitle"
        public const val SECONDARY_MEDIA_NAME: String =  "secondaryMediaName"
        public const val WAVE_ID: String =  "waveId"
        public const val NON_TYPICAL_SLEEP_REASON: String = "nonTypicalSleepReason"
        public const val FAMILY_ID: String = "familyId"
    }
}
